site_name: 小黑猫Bot帮助文档
site_description: 小黑猫猫的bot~
copyright: Copyright © 2022-Present 小黑猫Bot开发组. All rights reserved.
repo_url: https://github.com/LxhCatBot/lxhbot-docs
theme:
  name: material
  logo: "images/Logo.jpg"
  language: zh
  font: false
  palette:
    # 加载时自动日夜模式切换
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
extra_css:
  - stylesheets/extra.css
